### ISSUE TITLE
访问时偶尔会白屏

### ISSUE THREAD

**Issue by nnjzml** [nnez-icu/nnez.icu#6]
访问时偶尔会白屏, 疑似因使用 `cdn.jsdelivr.net` 的 cdn 服务导致, 建议更换

![图像 001](https://user-images.githubusercontent.com/110201636/221368919-09408a24-df36-4b19-9ca0-ff87f362a061.png)

![图像 002](https://user-images.githubusercontent.com/110201636/221369117-e5a4d68c-350e-48bd-9f62-4147230ea715.png)

**Comment by nnezdoticu** [comment]
Use cloudflare cdn alternative to fix.
